Repository matwjablonski/wdp-2403-01, pull requests merged in 2024-02, with the labels that each got.

#1 [WDP240301-3] Poprawa styli listy korzyści
  package.json
  src/components/common/FeatureBox/FeatureBox.js
  src/components/common/FeatureBox/FeatureBox.module.scss
  src/components/features/FeatureBoxes/FeatureBoxes.js
  yarn.lock
Labels: Ready

#11 [WDP240301-13] Dodanie komponentu Swipeable
  package.json
  src/components/common/Swipeable/Swipeable.js
  src/components/common/Swipeable/Swipeable.module.scss
  src/components/features/NewFurniture/NewFurniture.js
  yarn.lock
Labels: WIP, Ready

#7 [Wdp240301-1] - Brak zdjęć w kartach produktów.
  package-lock.json
  public/images/products/bed/aenean-ru-bristique-1.jpg
  public/images/products/bed/aenean-ru-bristique-10.jpg
  public/images/products/bed/aenean-ru-bristique-11.jpg
  public/images/products/bed/aenean-ru-bristique-12.jpg
  public/images/products/bed/aenean-ru-bristique-13.jpg
  public/images/products/bed/aenean-ru-bristique-14.jpg
  public/images/products/bed/aenean-ru-bristique-15.jpg
  public/images/products/bed/aenean-ru-bristique-16.jpg
  public/images/products/bed/aenean-ru-bristique-17.jpg
  public/images/products/bed/aenean-ru-bristique-18.jpg
  public/images/products/bed/aenean-ru-bristique-19.jpg
  public/images/products/bed/aenean-ru-bristique-2.jpg
  public/images/products/bed/aenean-ru-bristique-20.jpg
  public/images/products/bed/aenean-ru-bristique-21.jpg
  public/images/products/bed/aenean-ru-bristique-22.jpg
  public/images/products/bed/aenean-ru-bristique-23.jpg
  public/images/products/bed/aenean-ru-bristique-24.jpg
  public/images/products/bed/aenean-ru-bristique-3.jpg
  public/images/products/bed/aenean-ru-bristique-4.jpg
  public/images/products/bed/aenean-ru-bristique-5.jpg
  public/images/products/bed/aenean-ru-bristique-6.jpg
  public/images/products/bed/aenean-ru-bristique-7.jpg
  public/images/products/bed/aenean-ru-bristique-8.jpg
  public/images/products/bed/aenean-ru-bristique-9.jpg
  src/components/common/ProductBox/ProductBox.js
  src/components/common/ProductBox/ProductBox.module.scss
  src/components/common/ProductImage/ProductImage.js
  src/components/common/ProductImage/ProductImage.module.scss
  yarn.lock
Labels: Ready

#5 [WDP-2403-09] Stworzenie zmiennych dla animacji tła/tekstu/ikony
  src/components/common/Button/Button.module.scss
  src/components/common/FeatureBox/FeatureBox.module.scss
  src/components/layout/CompanyClaim/CompanyClaim.module.scss
  src/components/layout/MenuBar/MenuBar.module.scss
  src/styles/settings.scss
Labels: WIP

#12 WDP240301-7 add styles for select in product search menu
  src/components/features/ProductSearch/ProductSearch.module.scss
Labels: WIP

#3 [WDP240301-6] Dodanie starej ceny produktu
  src/components/common/Price/Price.js
  src/components/common/Price/Price.module.scss
  src/components/common/Price/Price.test.js
  src/components/common/ProductBox/ProductBox.js
  src/components/common/ProductBox/ProductBox.module.scss
  src/components/features/NewFurniture/NewFurniture.js
  src/redux/initialState.js
  src/styles/settings.scss
Labels: Ready

#10 [Wdp240301-8] - Użycie zmiennych do kolorów.
  src/components/common/Button/Button.module.scss
  src/components/common/FeatureBox/FeatureBox.module.scss
  src/components/common/ProductBox/ProductBox.module.scss
  src/components/features/NewFurniture/NewFurniture.module.scss
  src/components/features/ProductSearch/ProductSearch.module.scss
  src/components/layout/CompanyClaim/CompanyClaim.module.scss
  src/components/layout/Footer/Footer.module.scss
  src/components/layout/MenuBar/MenuBar.module.scss
  src/components/layout/TopBar/TopBar.module.scss
  src/styles/settings.scss
Labels: Ready
